### ISSUE TITLE
Include doesn't work with Windows paths separators like exclude does

### ISSUE THREAD

**Issue by wc-matteo** [AndersDJohnson/webpack-babel-env-deps#8]
`/node_modules\/`
vs
`/node_modules(\/|\\)`

**Comment by AndersDJohnson** [comment]
@wc-matteo This is causing issues for you on Windows?

**Comment by AndersDJohnson** [comment]
@wc-matteo I've just fixed and published to npm with `1.4.3`. Let me know whether it works for you. Thanks for reporting!
